apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: gitops-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  upgradeStrategy: Default
