apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: infra-6qqxq-worker
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: infra-6qqxq
spec:
  replicas: 4
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: infra-6qqxq
      machine.openshift.io/cluster-api-machineset: infra-6qqxq-worker
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: infra-6qqxq
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: infra-6qqxq-worker
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 16384
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: vlan141
          metadata:
            creationTimestamp: null
          numCPUs: 6
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: Datacenter
            datastore: ceph_hdd
            folder: /Datacenter/vm/infra-6qqxq
            resourcePool: /Datacenter/host/Synergy/Resources
            server: vcenter.elab.local
          template: infra-6qqxq-rhcos
          apiVersion: machine.openshift.io/v1beta1
