apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-deploy-acmtest
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    path: cluster-deploy/acmtest.eskom.demo
    repoURL: https://github.com/robotobibok/acm-argo-multicluster
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
