apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-config
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    path: cluster-config/infra.eskom.demo
    repoURL: "git@gitlab.eskom.demo:lab/ocp.git"
    targetRevision: main
  syncPolicy:
    automated:
      prune: false #nie kasujemy automatycznie
      selfHeal: true