apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-deploy-test
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    path: cluster-deploy/test.eskom.demo
    repoURL: https://github.com/robotobibok/acm-argo-multicluster
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      applicationsSync: create-only
      compare-options: IgnoreExtraneous
