apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: prod
    server: '*'
  sourceRepos:
  - '*'
