apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: prod
  namespace: prod
  labels:
    env: prod
    cloud: vSphere
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: managed-clusters
    rhsso: true
spec:
  baseDomain: eskom.demo
  clusterName: prod
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    vsphere:
      cluster: Synergy
      certificatesSecretRef:
        name: prod-vsphere-certs
      credentialsSecretRef:
        name: prod-vsphere-creds
      vCenter: vcenter.elab.local
      datacenter: Datacenter
      defaultDatastore: ceph_ssd
      network: vlan141
  provisioning:
    installConfigSecretRef:
      name: prod-install-config
    sshPrivateKeySecretRef:
      name: prod-ssh-private-key
    imageSetRef:
       #quay.io/openshift-release-prod/ocp-release:4.11.32-x86_64
      name: img4.12.9-multi-appsub
  pullSecretRef:
    name: prod-pull-secret
