kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: odf-thin-csi
  annotations:
    argocd.argoproj.io/sync-wave: "0"
provisioner: csi.vsphere.vmware.com
parameters:
  StoragePolicyName: odf-infra-dbjl4
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
