apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: dev.eskom.demo-worker
  namespace: 'acm-dev'
spec:
  clusterDeploymentRef:
    name: 'dev.eskom.demo'
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 2