apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: dev
  namespace: dev
  labels:
    env: dev
    cloud: vSphere
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: managed-clusters
spec:
  baseDomain: eskom.demo
  clusterName: dev
  controlPlaneConfig:
    servingCertificates: {}
  installAttemptsLimit: 1
  platform:
    vsphere:
      cluster: Synergy
      certificatesSecretRef:
        name: dev-vsphere-certs
      credentialsSecretRef:
        name: dev-vsphere-creds
      vCenter: vcenter.elab.local
      datacenter: Datacenter
      defaultDatastore: ceph_hdd
      network: vlan141
  provisioning:
    installConfigSecretRef:
      name: dev-install-config
    sshPrivateKeySecretRef:
      name: dev-ssh-private-key
    imageSetRef:
      #quay.eskom.demo/ocp4/openshift/release-images:4.12.10-x86_64
      name: img4.12.10-x86-64
  pullSecretRef:
    name: dev-pull-secret
