apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: dev.eskom.demo-infra
  namespace: 'acm-dev'
spec:
  clusterDeploymentRef:
    name: 'dev.eskom.demo'
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 2
  labels:
    node-role.kubernetes.io/infra: ""
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra