apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: 'dev.eskom.demo'
  namespace: 'acm-dev'
spec:
  clusterName: 'dev.eskom.demo'
  clusterNamespace: 'acm-dev'
  clusterLabels:
    cloud: vSphere
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true