apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dev-ns.yaml
- clusterimageset.yaml
- dev-clusterdeployment.yaml
- dev-managedcluster.yaml
- dev-managedclusterinfo.yaml
#- dev-machinepool-worker.yaml # zostajemy przy bazowej MP, szybszy deploy
#- dev-machinepool-infra.yaml # na dev bez infra node
- dev-klusterletaddonconfig.yaml
- secrets/dev-vsphere-certs.yaml
- secrets/dev-vsphere-creds.yaml
- secrets/dev-install-config.yaml
- secrets/dev-pull-secret.yaml
- secrets/dev-ssh-private-key.yaml
