apiVersion: v1
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: Validate=false,ServerSideApply=true
  name: alertmanager-main
  namespace: openshift-monitoring
type: Opaque