# Note this is resource reduced, this should not be taken as a production ready installation
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: central
  namespace: stackrox
spec:
  central:
    db:
      resources:
        requests:
          cpu: 2
          memory: "4G"
      persistence:
        persistentVolumeClaim:
          storageClassName: ocs-storagecluster-ceph-rbd
          claimName: central-db
    resources:
      requests:
        cpu: 1
        memory: "2G"
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    persistence:
      persistentVolumeClaim:
        storageClassName: ocs-storagecluster-ceph-rbd
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 2
    scannerComponent: Enabled
