apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dev-pull-secret
  namespace: dev
spec:
  encryptedData:
    .dockerconfigjson: AgADpjcIT/Q33uYKMOcfWu98h4rsb5/8uDZMElwEQkLj1hf4U1htE3TqBamXdiwNPxMDBickU1JVitb/JoEMznnR8+Mk8/WSpNmN9LEbnYhSZLLRrCroatqKQMKeULoX91paoaeh0Bti+m7visqqNjvdQQWpEVgKXzec3tt9ZsnraG3EB91OrzCivyH3AdYfkjp/WpZmYGZuOwXoRPB9hkWnKvsuNSu0mDIbb0axyDnKqm4edKYQ6HNn2g0XL3y4xZNHs4mcT8xYI97ydMYezbuiutt/mDhUviSfGxfKfOJ9/cnA3roRH+ZIXycUcoAsNRWPVn43NtCcDvnaE3CR/VBk11dMM9hJF5bcgb8taYi6zgdiberNywtKdvxiXvr5wETi66k1CArbJL4XiSKpKhU58+jM8KaRe1Qcf5jjKjUhbCkAqJxrgtTE7YMNTJI5+eW6Z0dmu+aqsAaLmQa+Q88NpkNVV9a+46ohhCaP7fnE1sOyoeFtXfXSm6ApjIjva4jS/ub1m3Fmc/q1zQ5TVFikueHXG9saPAKdpQL9oxnkTlHNpuvGhNTRpvKWQbuRlqctSRPPgtyUHCCYDGgo1hVZ2MlvcrziLcIMrhWEpDEsyNuhlDuJnyPQ5l42znjxKMkxWqsxIF8GkTctLhbrMlRaZulYYupGYI7vUBV+y0flReGiq8UF91i7teKFhjb91AmZRn37mDMBoqT+PR21opWQ6DuSiftg8VxD0Ao9nV6KET39HXP8Ne/J7II8kLmSmDuKRpoal54+tcpgdkK4I7Kc4HUoBNOq6cmUsc5Itocr0Pl5MLEW6gR8bqzG95Tlax057aKR
  template:
    metadata:
      creationTimestamp: null
      name: dev-pull-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson
