apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: infra-dbjl4-odf
  namespace: openshift-machine-api
  labels:
    machine.openshift.io/cluster-api-cluster: infra-dbjl4
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  replicas: 3
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: infra-dbjl4
      machine.openshift.io/cluster-api-machineset: infra-dbjl4-odf
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: infra-dbjl4
        machine.openshift.io/cluster-api-machine-role: odf
        machine.openshift.io/cluster-api-machine-type: odf
        machine.openshift.io/cluster-api-machineset: infra-dbjl4-odf
    spec:
      lifecycleHooks: {}
      metadata:
        labels:
          node-role.kubernetes.io/odf: ""
          cluster.ocs.openshift.io/openshift-storage: ""
      taints:
        - effect: NoSchedule
          key: node.ocs.openshift.io/storage
          value: "true"
      providerSpec:
        value:
          numCoresPerSocket: 2
          diskGiB: 120
          snapshot: ''
          userDataSecret:
            name: worker-user-data
          memoryMiB: 24576
          credentialsSecret:
            name: vsphere-cloud-credentials
          network:
            devices:
              - networkName: vlan141
          metadata:
            creationTimestamp: null
          numCPUs: 8
          kind: VSphereMachineProviderSpec
          workspace:
            datacenter: Datacenter
            datastore: ceph_ssd
            folder: /Datacenter/vm/infra-dbjl4
            resourcePool: /Datacenter/host/Synergy/Resources
            server: vcenter.elab.local
          template: infra-dbjl4-rhcos
          apiVersion: machine.openshift.io/v1beta1
