apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

# resources:
# - zabbix-agent-ds.yaml

# patches:
# - target:
#     group: apps
#     version: v1
#     kind: DaemonSet
#     name: zabbix-agent
#   patch: zabbix-agent-ds.yaml

patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: zabbix-agent
  patch: |-
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: zabbix-agent
    spec:
      template:
        spec:
          tolerations:
            - key: node-role.kubernetes.io/master
              operator: Exists
              effect: NoSchedule
            - key: node-role.kubernetes.io/infra
              operator: Exists
              effect: NoSchedule
