apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base

patches:
- target:
    group: apps
    version: v1
    kind: DaemonSet
    name: zabbix-agent
  patch: zabbix-agent-ds.yaml
