---
apiVersion: automationcontroller.ansible.com/v1beta1
kind: AutomationController
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: kruk
  namespace: ansible-automation-platform
spec:
  replicas: 1