apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgAhyz7zkTDyY86p9vW1mbynJRpU0jFZ8fMC0lAzP2SY/2AbPhWt1cA6JG1q5ab01cl8FCioNn5hUJ/5yZ3Mtvualv31gwWZINCnsD2V1f2C6cLP3XWtE7fJOd76bEZnQi7aCY8HmgWm/zhj7eEj9/bn73PJNqbI21y0e2pS99A2XO/6I+bWT8taOoybe7QWn7lvHu6BSX31I//yD+uFTLkI+W6OJYxSNfxrYMT8NnXbuZxvn2Nf45AHQZnBHqOPimdoQw2jk91Ifs2IwOE9NuVXrsaIuJ2x0O1Na7YGAcntERpcShxjIlWXcC1UfuJmmAoeH76g1Nf6VLznxO3gRm2fK+kuROKJZYtiYQtawn6DQH70SjFVx0voxM7YEGOEtF1DlKEjckcUhaLh+1XPWxJ1rPzUcVkzYzVRT03XxcCgKE4GwHPB7SHFjghrs4ufYNS3kyi4ywIRpKnwzcAlMM0+XJ8zX0kjhXBQQC6mDujaUGo1mXlOe0qSiX+gmZSogRuA0E7DXrE0WplI7KPIA7vRDLjew50lWcpZCGfhJTTUe/fiiC7Ifbk5/ZheXa8Lcj7kKreOXzBQrWPKRrE8KWJPdhXk3s3xqt7RxxAJCpOb0itG3HSMTOdgs1kPXyHuSBaH8IAc2jRp+0U0JTGRk4Lk33sOF4iZZ2XLNib1BMyds7DBa9a1kCUmk8iARYW62gi4Bstw2UF5zznOsjW03ZGuC6SJm3C2cgNDK78ZDXO6Kq1Eo2aKUVRPqnPbPoTI8qZHHzMFihNHV3gDEvmXuIUfbA8G
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque