apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: dev-worker
  namespace: dev
spec:
  clusterDeploymentRef:
    name: dev
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 100
  replicas: 3