apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  encryptedData:
    htpasswd: AgBqSLec6IoXqKOlLsQ6D0kgfXmE+BpAC2Eu4VeRQUU9tUoyQVtJ5vcBovUUotK4vdbQfM2rIXOtp3k3zxvIb0rrRqwN1lZgQUIJ9C30I7S70cmiayIPpyxz129hmAlU8ZGKVQFuZmUcI827W0URhwUzSTc5VD5pDXI23CDFPlr9CtSANh1gaWIA60fnXJFgtcOBosTtOd5AzbQcPuTJbf0N3cm/jllsSbO7lJbkVHcXjo9vtXua4zFZgnd0bi0KqHzhW0iBWw5PFlNQJGXe0YD1kyEXFeZjUy7RXTbE1qdgZl6SoeNJV5QgeiW2zLiJny4VaiUHhnMw9MWaIXBH/8c9VLWu9O8YCoaHGQXHEI97COg3mE8kia/iZvxe//KfiDhK8eR7ucFUHRCMqWZiulZSJdU8ImbvuyRxeeQbz5BSF+CvZ/EFgFTzXWraZs7rtc24trEa4CHxJ6CC/mNKw5ilNEYLow4Rrx+60uQs+JxmGLDGEdhmNPCsCjFBVcJeWpQ2O6vWTNa8vRWYYCoZ4Ph9r/ZBDymHDwBiwPY/kPLYlirEtTbCQZuGBM5LwBjVcG1umP4S5IO+eTsueFkVaoEEtNITxZSEXMAuSkbigG1ht8K79+yf+dxeqBpO1zrJ3+EpQZdIg+C1+FTate658XItfJ6zLfs2Sp/tbfzqEBDhPB+MLb0LJIJ6ukX0aELdX0D8G0qYStHrNGLYiw1di6BFwA6pAKrCnRvllTcHur37pQg8Sqpmx5O1vmcqtggh9bfJXLbEGHoxzayfWem99D2jjYct
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque