apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- prod-ns.yaml
- prod-clusterdeployment.yaml
- prod-managedcluster.yaml
- prod-managedclusterinfo.yaml
#- prod-machinepool-worker.yaml #niepotrzebna, mozna sterowac iloscia workerow z install-config
- prod-machinepool-infra.yaml
- prod-klusterletaddonconfig.yaml
- secrets/prod-vsphere-certs.yaml
- secrets/prod-vsphere-creds.yaml
- secrets/prod-install-config.yaml
- secrets/prod-pull-secret.yaml
- secrets/prod-ssh-private-key.yaml