apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: prod-worker
  namespace: prod
spec:
  clusterDeploymentRef:
    name: prod
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
  replicas: 3