apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
#- ../../manifests/namespaces
- ../../manifests/oauth-htpasswd/overlays/prod
- ../../manifests/rbac/base
- ../../manifests/machine-set/prod.eskom.demo
#- ../../manifests/ingress-config
#- ../../manifests/imageregistry-config
#- ../../manifests/monitoring-config
- ../../manifests/alertmanager/overlays/prod