apiVersion: cluster.open-cluster-management.io/v1
kind: Placement
metadata:
  name: managed-clusters-placement
  namespace: openshift-gitops
spec:
  clusterSets:
    - managed-clusters
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
                - test
                - prod