apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
spec:
  # Number of desired image registry pods
  replicas: 1
  # Cannot use ReadWriteOnce access mode with RollingUpdate rollout strategy
  rolloutStrategy: Recreate
  # Configure persistent storage for the image registry.
  storage:
    managementState: Managed
    pvc:
      claim: registry
    s3: null
