apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alertmanager
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - name: infra
        cluster: in-cluster
  template:
    metadata:
      name: "{{ name }}-alertmanager"
    spec:
      project: "{{ name }}"
      source:
        repoURL: "git@gitlab.eskom.demo:lab/ocp.git"
        targetRevision: main
        path: manifests/alertmanager/overlays/{{ name }}
      destination:
        name: "{{ cluster }}"
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
