apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../manifests/namespaces
- ../../manifests/oauth-htpasswd/overlays/infra
- ../../manifests/rbac/overlays/infra
- ../../manifests/gitops-config
- ../../manifests/acm-policy-sso