apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../manifests/namespaces
- ../../manifests/oauth-htpasswd/overlays/infra
- ../../manifests/rbac/overlays/infra
- ../../manifests/gitops-config
#- ../../manifests/acm-policy-sso
#- ../../manifests/acm-policy-webterminal # failed to sync cluster https://172.30.0.1:443: failed to load initial state of resource DevWorkspace.workspace.devfile.io: Internal error occurred: error resolving resource
- ../../manifests/acm-policy-etcd-encrypt
#- ../../manifests/acm-policy-odf # nie mozna uruchomic storagesystem, moze za wysoka wersja vmware
#- ../../manifests/acm-policy-acs # problem z violation, pewnie jakis bug: violation - subscriptions [rhacs-operator] in namespace rhacs-operator is missing, and cannot be created, reason: `subscriptions.operators.coreos.com "rhacs-operator" already exists`
- ../../manifests/machine-set/infra.eskom.demo
- ../../manifests/alertmanager/overlays/infra
#- ../../manifests/odf-operator
#- ../../manifests/odf-instance