apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: test
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    name: test
    server: 'https://api.test.eskom.demo:6443'
  sourceRepos:
  - '*'