apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: htpass-secret
  namespace: openshift-config
spec:
  encryptedData:
    htpasswd: AgBXfzW7H8i6IC4suG4UVcJ822GOLN/xkxOi6FQoResLSNkx0gNvAkShGqNexU8WB7J/vX7rgNKYxBLV9BZ9ZNclAldMQCDwoN5QlwtQ3ltZ8MLZOHNlQOpHL/9bOiGxI1BVxULBT2pDrtkFESHHMh6ntzOrgmsqqV4Z44vcJq13dZdpykxaQ27oPc4VyIbxnbIk99C8T8Q/miCE6VZUqJLl5PRbQGtkfk+ZBRwLNnJdiuLlUWryxxd6MVWBFIpLFOqkaXjLx51l/fvHBVHo4Zmp/FwXOsPh843Sy6T49KNwsMOJvaCbZe5srwM3QOlvCDgSInvS4BwMTNTTa4jzGlyUnewgLQ99RrFxFNj6L2xbyhsidwf2HTwJO+UVCp+fO1vCzi2+y9MxLDfD/+DHXzuAS3+a2/uCKCnsBO7DjUVO74sNTfx7kZMZ2WrfOy3LX2CDM/fURhZ67EuSB9TeIeKkNxvfbvg89TUoNPHRMoMYChbhFLW2Da06E/idKLniki6EMa5WydR6KW6zY1kO4MKxwoqYgWNyas/Vl8AX9yc677PKvBKiZ/tBwTHvoSBeAVX3NU5aSBAV+OREZooYqGnJJPBPqcCiBZpVSvGg372NS56dRABLcbjCyKebmghCvuX1/oEU/WpWIf7gnOKRwewxbB29WfiMicC4FD3nYsd78hNq0mO4gpQ982Aw1zR91pV9H16aUthJoWSGHNTbNRpWQOzpi3v1ALHQ1V5lhEXA34VXCMyKWWXgAhBCsnBA0FIylaYcOkG75PzTejCGfdT2SGcN
  template:
    metadata:
      creationTimestamp: null
      name: htpass-secret
      namespace: openshift-config
    type: Opaque