apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: webapp
  source:
    repoURL: https://github.com/pbartczak/gitops-app-config.git
    targetRevision: main
    path: webapp/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: webapp-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
