apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: webapp
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  description: Prosta strona internetowa
  sourceRepos:
    - "https://github.com/pbartczak/*"
  destinations:
    - namespace: "webapp-*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: "Namespace"
