apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: local-cluster
  namespace: stackrox
spec:
  clusterName: local-cluster
  admissionControl:
    listenOnCreates: false
    listenOnEvents: true
    listenOnUpdates: false
  perNode:
    collector:
      collection: KernelModule
      imageFlavor: Regular
    taintToleration: TolerateTaints
  centralEndpoint: "central-stackrox.apps.infra.eskom.demo:443"