apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: test
  namespace: test
spec:
  clusterDeploymentRef:
    name: test
  name: worker
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 100
  replicas: 2