apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: 'test.eskom.demo-infra'
  namespace: 'acm-test'
spec:
  clusterDeploymentRef:
    name: 'test.eskom.demo'
  name: infra
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 100
  replicas: 2
  labels:
    node-role.kubernetes.io/infra: ""
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra