apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-gitops-config
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
  project: infra
  source:
    path: manifests/gitops-config
    repoURL: https://github.com/robotobibok/acm-argo-multicluster
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
